### ISSUE TITLE
[Bug] Water doesn't work correctly when placed down. 

### ISSUE THREAD

**Issue by gazingstorm** [Treetrain1/Survival-Remastered#17] opened 2022-08-17 22:33 UTC
**Describe the bug**

Water buckets, when placed down, spread out, and the water that is not the source becomes a water block when you remove the source instead of disappearing. 

**To Reproduce**

Place down a water bucket. After it stops flowing water out, remove the source block. The remaining water blocks which should disappear stay instead. 

**Expected behavior**
What did you expect to happen before finding this bug?

The water would be completely removed when the source is removed.

**Screenshots**
![huge_2022-08-17_18 32 22](https://user-images.githubusercontent.com/111467090/185255215-d764b999-ca49-4c32-901f-25de8be51305.png)

**Setup:**
Windows 11
Version 2

**Additional context**

**Comment by EthanRStokes** [comment] 2022-08-20 14:55
I am unable to reproduce this issue
Has the problem been solved on its own or is it repetitive?

**Comment by EthanRStokes** [comment] 2022-08-23 02:29
I was just able to reproduce this issue
I'll look into it

**Comment by EthanRStokes** [comment] 2022-10-09 18:31
I've found the cause of this and fixed it.
The fix will be in the next update.

**Closed as completed** 2022-12-04 01:42 UTC
Labels: bug, fix on release
